apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-platform-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  project: platform
  source:
    repoURL: https://github.com/josefloressv/kcd_colombia_platform.git
    targetRevision: HEAD
    path: addons
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
